# Generated by Django 5.1.4 on 2025-05-31 15:02

import django.db.models.deletion
from django.db import migrations, models

def crear_categorias(apps, _schema_editor):
    Categoria = apps.get_model('market', 'Categoria')
    categorias = ['Consolas', 'Videojuegos', 'Accesorios', 'Figuras', 'Ropa', 'Memoria USB']
    for nombre in categorias:
        Categoria.objects.get_or_create(nombre=nombre)
        
class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.categoria'),
        ),
        migrations.RunPython(crear_categorias),
    ]
