# Generated by Django 5.1.4 on 2025-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
