# Generated by Django 5.1.4 on 2025-06-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_carrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
