# Generated by Django 5.1.4 on 2025-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_pedido_lineapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(default='Dirección pendiente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='Nombre pendiente', max_length=100),
        ),
    ]
